# Generated by Django 5.1.3 on 2025-03-09 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_campaign_min_balance_alter_campaign_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='wallets/', verbose_name='Logo'),
        ),
    ]
